### ISSUE TITLE
java.lang.NoClassDefFoundError: org/komamitsu/fluency/Fluency$Config

### ISSUE THREAD

**Issue by muceres** [fluent/kafka-connect-fluentd#5]
Hello,

### Previous steps done :
- setting up Apache Kafka throught confluent
- Downloading kafka-connect-fluentd
- Building jar

### Current behavior :
When I try to run kafka-connect-fluentd with the FluentdSinkConnector.properties file, I encounter the following error :

`[2017-11-08 15:00:55,019] ERROR Task FluentdSinkConnector-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:148)
java.lang.NoClassDefFoundError: org/komamitsu/fluency/Fluency$Config
	at org.fluentd.kafka.FluentdSinkTask.start(FluentdSinkTask.java:46)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:145)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.komamitsu.fluency.Fluency$Config
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
`

I placed kafka-connect-fluentd in confluent-3.3.0/share/java inside the confluent repository and I have the following set up for the CLASSPATH : 
`export CLASSPATH=/home/ubuntu/confluent-3.3.0/share/java/kafka-connect-fluentd/*
`
### Current installation:
   - Confluent 3.3.0 :
      - Apache Kafka 0.11.0.0
   - Ubuntu 16.04.3 LTS
   - OpenJDK 1.8.0_131

I guess there is an issue with the jar building since I get a NoClassDefFoundError but I have no clue on how to slove this. The fluency dependency has correctly been indicated in the build.gradle. Can you shed some light on this ?

Thank you,

**Comment by okkez** [comment]
Which do you use kafka-connect-fluentd-0.0.1.jar or kafka-connect-fluentd-0.0.1-all.jar ?
If you use kafka-connect-fluentd-0.0.1.jar, you must install dependencies by yourself (such as fluency and influent).

**Comment by muceres** [comment]
Thank you I builed the all.jar. I thought that dependencies were installed within the jar by default.
